var varclass,varclass1;

document.getElementById("panel1").innerHTML='<div class="col-sm-2"> <div class="slis1"><ul>'
                  + '<li class="l1">TOPWEAR</li>'
                    + '<li id="list37" onclick="openit(36)">T-Shirts</li>'
				    + '<li id="list38" onclick="openit(37)">Casual Shirts</li>'
				    + '<li id="list39" onclick="openit(38)">Formal Shirts</li>'
				    + '<li id="list40" onclick="openit(39)">Sweaters & Sweatshirts</li>'
				    + '<li id="list41" onclick="openit(40)">Jackets</li>'
				    + '<li id="list42" onclick="openit(41)">Blazers & Coats</li>'
				    + '<li id="list43" onclick="openit(42)">Suits</li>'
				   + ' <li id="list44" onclick="openit(43)">Clothing Fabric</li>'
			      + '</ul>'
  + '</div>'
 + '</div>'
    + '<div class="col-sm-2"> <div class="slis1"><ul>'
                   + ' <li class="l1">BOTTOMWEAR</li>'
                 + ' <li id="list45" onclick="openit(44)">Jeans</li>'
				 + ' <li id="list46" onclick="openit(45)">Casual Trousers</li>'
				 + ' <li id="list47" onclick="openit(46)">Formal Trousers</li>'
				  + '<li id="list48" onclick="openit(47)">Shorts</li>'
				  + '<li id="list49" onclick="openit(48)">Trackpants/Joggers</li>'
				+ ' </ul>'
+ '</div>'
+ '</div>'
   + ' <div class="col-sm-2"><div class="slis1"><ul>'
                  + ' <li class="l1">SPORTS & ACTIVE WEAR</li>'
                 + ' <li id="list50" onclick="openit(49)">Active T-Shirts</li>'
				 + ' <li id="list51" onclick="openit(50)">Trackpants & Shorts</li>'
				 + ' <li id="list52" onclick="openit(51)">Jackets & Sweatshirts</li>'
				  + '<li id="list53" onclick="openit(52)">Swimwear</li>'
				  + '<li id="list54" onclick="openit(53)">Smart Wearables</li>'
				  + '<li id="list55" onclick="openit(54)">Sports Accesories</li>'
				 + ' <li id="list56" onclick="openit(55)">Sports Equipments</li>'
				   + '<li id="list57" onclick="openit(56)">Sport Shoes</li>'
			    + '</ul>'
+ '</div>'
+ '</div>'

+ '<div class="col-sm-2"><div class="slis1" style="margin-left:10px"><ul><li class="l1">FOOTWEAR</li>'
                  + '<li id="list58" onclick="openit(57)">Casual Shoes</li>'
				  + '<li id="list59" onclick="openit(58)">Sport Shoes</li>'
				  + '<li id="list60" onclick="openit(59)">Formal Shoes</li>'
				  + '<li id="list61" onclick="openit(60)">Sandals & Floaters</li>'
				  + ' <li id="list62" onclick="openit(61)">Flip Flops</li>'
				  + '<li id="list63" onclick="openit(62)">Socks</li>'
			   + ' </ul>'
+ '</div>'
+ '</div>'
+ '<div class="col-sm-2"><div class="slis1"><ul>'
                  + ' <li class="l1">INNERWEAR & SLEEPWEAR</li>'
                 + ' <li id="list64" onclick="openit(63)">Briefs & Trunks</li>'
				 + ' <li id="list65" onclick="openit(64)">Boxers</li>'
				 + ' <li id="list66" onclick="openit(65)">Vests</li>'
				 + ' <li id="list67" onclick="openit(66)">Sleepwear & Loungewear</li>'
				  + ' <li id="list68" onclick="openit(67)">Thermals</li>'
			   + ' </ul>'
+ '</div></div>'



+ '<div class="col-sm-2">'
+ '<div class="slide"><img class="img-responsive img-rounded" src="../res/images/banner3.jpeg" style="width:190px; height:auto;margin-top:90px;margin-left:10px"></div></div>'


document.getElementById("panel2").innerHTML='<div class="col-sm-2">'
   + '<div class="slis1"><ul>'
                  + '<li class="l1" >INDIAN & FUSION WEAR</li>'
                + ' <li id="list1" onclick="openit(0)">Kurtas & Suits</li>'
				+ ' <li id="list2" onclick="openit(1)" >Kurtis,Tunics & Tops</li>'
				+ ' <li id="list3" onclick="openit(2)">Ethnic Dresses</li>'
				+ ' <li id="list4" onclick="openit(3)">Leggings,Salwars & Churidars</li>'
				+ ' <li id="list5" onclick="openit(4)">Skirts & Palazzos</li>'
				+ '  <li id="list6" onclick="openit(5)">Sarees & Blouses</li>'
			   + '</ul>'
+ '</div>'
+ '</div>'

+ '<div class="col-sm-2">'
+ '<div class="slis1"><ul>'
                 + ' <li class="l1">WESTERN WEAR</li>'

                  + '<li id="list11" onclick="openit(10)">Dress Material</li>'
				  + '<li id="list12" onclick="openit(11)">Lehenga Choli</li>'
				  + '<li id="list13" onclick="openit(12)">Dupattas & Shawls</li>'
				 + '<li id="list14" onclick="openit(13)" >Jackets & Waistcoats</li>'
				 + ' <li id="list15" onclick="openit(14)">Dresses & Jumpsuits</li>'
				 + '<li id="list16" onclick="openit(15)">Tops,T-Shirts & Shirts</li>'
			   + '</ul>'
+ '</div></div>'

+ '<div class="col-sm-2">'
+ '<div class="slis1"><ul>'
                  + '<li class="l1">LINGERIE & SLEEPWEAR</li>'
                 + '<li id="list20" onclick="openit(19)">Bras,Lingerie Sets</li>'
				  + '<li id="list21" onclick="openit(20)">Briefs</li>'
				  + '<li id="list22" onclick="openit(21)">Shapewear</li>'
				 + '<li id="list23"onclick="openit(22)" >Sleepwear & Loungewear</li>'
				 + '<li id="list24"onclick="openit(23)" >Swimwear</li>'
				 + '<li id="list25"onclick="openit(24)" >Camisoles & Thermals</li>'
				+ '</ul>'
+ '</div></div>'

+ '<div class="col-sm-2">'
+ '<div class="slis1"><ul><li class="l1">FOOTWEAR</li>'
                + '<li id="list26" onclick="openit(25)">Flats & Casual Shoes</li>'
				+ '<li id="list27" onclick="openit(26)">Heels</li>'
				+ '<li id="list28" onclick="openit(27)">Boots</li>'
				+ '<li id="list29" onclick="openit(28)">Sports Shoes & Floaters</li>'
			   + ' </ul>'
+ '</div>'
+ '</div>'

+ '<div class="col-sm-2">'
+ '<div class="slis1"><ul>'
                 + '<li class="l1">SPORTS & ACTIVE WEAR</li>'
                 + '<li id="list30" onclick="openit(29)">Clothing</li>'
				 + '<li id="list31" onclick="openit(30)">Footwear</li>'
				 + '<li id="list32" onclick="openit(31)">Sports Accessories</li>'
				 + '<li id="list33" onclick="openit(32)">Sports Equipment</li>'
			    + '</ul>'
+ '</div></div>'

+ '<div class="col-sm-2">'
+ '<div class="slide"><img class="img-responsive img-rounded" src="../res/images/banner4.jpeg" style="width:190px; height:auto;margin-top:70px;margin-left:10px"></div>'
+ '</div>'

document.getElementById("panel3").innerHTML='<div class="col-sm-2">'
  + '<div class="slis1"><ul>'
									+ '<li class="l1">BED LINEN AND FURNISHING</li>'
									+ '<li id="list72" onclick="openit(36)">Bedsheets</li>'
									+ '<li id="list73" onclick="openit(36)">Bedding Sets</li>'
									+ '<li id="list74" onclick="openit(36)">Blankets Quilts and Dohars</li>'
									+ '<li id="list75" onclick="openit(36)">Pillows & Pillow Covers</li>'
									+ '<li id="list76" onclick="openit(36)">Bed Covers</li>'
								+ '</ul>'
							+ '</div></div>'

						+ '<div class="col-sm-2">	<div class="slis1">'
								+ '<ul>'
									+ '<li class="l1">BATH</li>'
									+ '<li id="list77" onclick="openit(36)">Bath Towels</li>'
									+ '<li id="list78" onclick="openit(36)">Hand and Face Towels</li>'
									+ '<li id="list79" onclick="openit(36)">Beach Towels</li>'
									+ '<li id="list80" onclick="openit(36)">Towels Set</li>'
									+ '<li id="list81" onclick="openit(36)">Bath Rugs</li>'
									+ '<li id="list82" onclick="openit(36)">Bath Robes</li>'
									+ '<li id="list83" onclick="openit(36)">Bathroom Accessories</li>'
								+ '</ul>'
							+ '</div></div>'
						
						+ '<div class="col-sm-2"><div class="slis1">'
								+ '<ul>'
									+ '<li class="l1">FLOORING</li>'
									+ '<li id="list37" onclick="openit(36)">Carpets</li>'
									+ '<li id="list37" onclick="openit(36)">Floor Mats</li>'
									+ '<li id="list37" onclick="openit(36)">Door Mats</li>'
								+ '</ul>'
							+ '</div></div>'

						+ '<div class="col-sm-2">	<div class="slis1">'
								+ '<ul>'
									+ '<li class="l1">HOME DECOR</li>'
									+ '<li id="list37" onclick="openit(36)">Plants & Planters</li>'
									+ '<li id="list37" onclick="openit(36)">Aromas & Candles</li>'
									+ '<li id="list37" onclick="openit(36)">Clocks</li>'
									+ '<li id="list37" onclick="openit(36)">Mirrors</li>'
									+ '<li id="list37" onclick="openit(36)">Wall Decor</li>'
									+ '<li id="list37" onclick="openit(36)">Wall Shelves</li>'
									+ '<li id="list37" onclick="openit(36)">Fountains</li>'
									+ '<li id="list37" onclick="openit(36)">Showpieces</li>'
									+ '<li id="list37" onclick="openit(36)">Lamps and lighting</li>'
									+ '<li id="list37" onclick="openit(36)">Storage</li>'
								+ '</ul>'
							+ '</div></div>'
						
						+ '<div class="col-sm-2">	<div class="slis1">'
								+ '<ul>'
									+ '<li class="l1">KITCHEN & TABLE</li>'
									+ '<li id="list37" onclick="openit(36)">Tableware & Serveware</li>'
									+ '<li id="list37" onclick="openit(36)">Cookware & Kitchen Tools</li>'
									+ '<li id="list37" onclick="openit(36)">Kitchen Storage</li>'
									+ '<li id="list37" onclick="openit(36)">Table Covers & Furnishings</li>'
								+ '</ul>'
							+ '</div></div>'

+ '<div class="col-sm-2">'
+ '<div class="slide"><img class="img-responsive img-rounded" src="../res/images/banner6.jpeg" style="width:190px; height:auto;margin-top:110px;margin-left:10px"></div></div>'

 for(listtt=1;listtt<=71;listtt++){ var a=listtt-1;
document.getElementById("list"+listtt).innerHTML=secondaryclass[listtt-1];

	}
  ;

  
  
    
 function openit(varclass){
	   location.reload();
	   window.open("display.html?varclass1="+varclass,"_self");
	    
   }
 
  